import Head from 'next/head';
import {Inter} from 'next/font/google';
import styles from '@/styles/Home.module.css';
//components
import NavBar from '@/components/navbar/navbar';
import Banner from '@/components/banner/banner';
import Card from '@/components/card/card';
import SectionCards from '@/components/card/sectionCards';
import {getVideos} from '@/lib/videos';

const inter = Inter({subsets: ['latin']});

export async function getServerSideProps() {
    const disneyVideos = getVideos();

    return {props: {disneyVideos}};
}

export default function Home({disneyVideos}) {
    return (
        <>
            <Head>
                <title>Movie App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <NavBar username='maggyedozie@gmail.com' />
            <Banner
                title='Clifford the red dog'
                subTitle='a very cute dog'
                imgUrl='/static/clifford.webp'
            />
            <div className={styles.sectionWrapper}>
                <SectionCards
                    title='Disney'
                    videos={disneyVideos}
                    size='large'
                />
                <SectionCards
                    title='Productivity'
                    videos={disneyVideos}
                    size='medium'
                />
            </div>
        </>
    );
}
