import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
//components
import Banner from '@/components/banner/banner'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>movie app</h1>
<Banner title="Clifford the red dog"
  subTitle ="a very cute dog"
  imgUrl="/static/clifford.webp"
/>
          </>
  )
}
