import Head from 'next/head';
import {Inter} from 'next/font/google';
import styles from '@/styles/Home.module.css';
//components
import NavBar from '@/components/navbar/navbar';
import Banner from '@/components/banner/banner';
import Card from '@/components/card/card';
import SectionCards from '@/components/card/sectionCards';
import {getVideos, getPopularVideos} from '@/lib/videos';
import {magic} from '../lib/magicClient';
// const inter = Inter({subsets: ['latin']});

export async function getServerSideProps() {
    const disneyVideos = await getVideos('disney trailer');
    const productivityVideos = await getVideos('productivity');
    const travelVideos = await getVideos('travel');
    const popularVideos = await getPopularVideos('popular');

    return {
        props: {
            disneyVideos,
            popularVideos,
            travelVideos,
            productivityVideos,
        },
    };
}

export default function Home({
    disneyVideos,
    popularVideos,
    travelVideos,
    productivityVideos,
}) {
    console.log({magic});

    return (
        <>
            <Head>
                <title>Watchflix</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div className={styles.main}>
                <NavBar username='maggyedozie@gmail.com' />
                <Banner
                    videoId='4zH5iYM4wJo'
                    title='Clifford the red dog'
                    subTitle='a very cute dog'
                    imgUrl='/static/clifford.webp'
                />
                <div className={styles.sectionWrapper}>
                    <SectionCards
                        title='Disney'
                        id={disneyVideos.id}
                        videos={disneyVideos}
                        size='large'
                    />
                    <SectionCards
                        title='Travel'
                        videos={travelVideos}
                        size='small'
                    />
                    <SectionCards
                        title='Productivity'
                        videos={productivityVideos}
                        size='medium'
                    />
                    <SectionCards
                        title='Popular'
                        videos={popularVideos}
                        size='small'
                    />
                </div>
            </div>
        </>
    );
}
